
image: Visual Studio 2017

configuration:
  - Release

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    QT5: C:\Qt\5.11.1\msvc2017_64

before_build:
- rm -rf build
- set Path=%QT5%\bin;%Path%
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%"
- CMAKE_PROJECT_VERSION=`cat build/CMakeCache.txt | grep CMAKE_PROJECT_VERSION:STATIC | cut -d'=' -f 2`
- export CMAKE_PROJECT_VERSION

build_script:
- cmake --build build --config Release

after_build:
- cmake --build build --config Release --target package

deploy:
  release: RocRailBBTCalculator-v$(CMAKE_PROJECT_VERSION)
  description: 'Initial release'
  provider: GitHub
  auth_token:
    secure: i6EnQVg7Lv4pMFPuXqtCNeTTxE6Vk/azuJpCzEg3tSAko7KMGwaX4KzJRViMivF8
  artifact: build/rocrailBBTCalculator-*.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

