
image: Visual Studio 2017

configuration:
  - Release

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    QT5: C:\Qt\5.11.1\msvc2017_64

before_build:
- set Path=%QT5%\bin;%Path%
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%"

build_script:
- cmake --build build --config Release

after_build:
- cmake --build build --config Release --target package

artifacts:
- path: build/rocrailBBTCalculator-*.exe