
image: Visual Studio 2017

configuration:
  - Release

environment:
  matrix:
  - QT5: C:\Qt\5.11.1\msvc2017_64

before_build:
- set Path=%QT5%\bin;%Path%
- cmake -H. -Bbuild "-DCMAKE_PREFIX_PATH=%QT5%"

build_script:
- cmake --build build --config "%CONFIGURATION%"

after_build:
- cmake --build build --config "%CONFIGURATION%" --target package

artifacts:
- path: build/rocrailBBTCalculator-*.exe